Error handler
joaquinvalentin/rails_training pull request #8
Opened 2021-11-12 19:04 UTC by joaquinvalentin

Just review the last three commits:

1. Add error handling (with Blueprinter)
2. Change returns to render_error
3. Change serializer to Blueprinter and remove old gem

The previous commits are from [User auth PR](https://github.com/joaquinvalentin/rails_training/pull/7)

In this branch I've done the error handle. I changed the `jsonapi-serializer` gem to `Blueprinter` because this is more useful for this issue and I see that it's the most common gem for serialization in XL.

2021-11-15 16:05 UTC, guillezorron commented on config/errors.yaml
> +  :description: 'Invalid Parameter'
Missing newline at end of file

2021-11-15 16:05 UTC, guillezorron commented on app/controllers/api/v1/users_controller.rb
> +      render_error(4022, user.errors.messages[:error])
Please use a different error code here like 4023. The error codes need to be really specific.

2021-11-15 16:05 UTC, guillezorron commented on config/errors.yaml
> +  :description: 'Invalid Parameter'
Also the description is too generic for this error, the description should be something like: 'Cannot update profile due to invalid paramater'

2021-11-15 16:05 UTC, guillezorron commented on config/errors.yaml
> +  :description: 'You are not authorized to do this action'
```suggestion
  :description: 'User can not be deleted or updated due to user not found'
```

2021-11-15 16:05 UTC, guillezorron commented on config/errors.yaml
> +  :http_status: 401
404 should be here

2021-11-15 16:05 UTC, guillezorron commented on spec/controllers/api/v1/users_controller_spec.rb
> +        expect(JSON.parse(response.body)['details']).to eql("Couldn't find User with 'id'=0")
Maybe we can check in each one the error code what do you think?

2021-11-16 12:52 UTC, joaquinvalentin commented on config/errors.yaml
> +  :http_status: 401
It's error 4000

2021-11-17 14:04 UTC, guillezorron approved these changes

2021-11-17 14:05 UTC, guillezorron requested changes
error

2021-11-17 14:36 UTC, MarcosFierro commented on app/controllers/api/v1/users_controller.rb
> +    render json: UserSerializer.render(user)
Nice

2021-11-17 14:37 UTC, MarcosFierro commented on app/controllers/api/v1/users_controller.rb
> +      render_error(4022, user.errors.messages[:error])
👍🏼

2021-11-17 14:37 UTC, MarcosFierro commented on app/controllers/concerns/authenticable.rb
> +    decoded = JsonWebToken.decode(header.split(' ').last)
👍🏼

2021-11-17 14:39 UTC, MarcosFierro commented on lib/error.rb
> +  end
💯

2021-11-17 14:43 UTC, MarcosFierro approved these changes
Cool Error handling

2021-11-17 14:49 UTC, guillezorron approved these changes

2021-11-18 13:42 UTC, merged